=== cooladm1n/marvin/apps/marvin_pdu2/priv/json_schema/object/channel.json
{
    "id": "file://object/channel",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "https://discordapp.com/developers/docs/resources/channel#channel-object",
    "type": "object",
    "required": ["id", "type"],
    "properties": {
        "id": {"$ref": "file://type/snowflake"},
        "type": {"type": "number", "inclusiveMinimum": 0, "inclusiveMaximum": 4},
        "guild_id": {"$ref": "file://type/snowflake"},
        "position": {"type": "number", "inclusiveMinimum": 0},
        "permission_overwrites": {"type": "array", "items": {"$ref": "file://object/permission_overwrite"}},
        "name": {"type": "string", "minLength": 2, "maxLength": 100},
        "topic": {"oneOf": [
            {"type": "null"},
            {"type": "string", "minLength": 0, "maxLength": 1024}
        ]},
        "nsfw": {"type": "boolean"},
        "last_message_id": {"oneOf": [
            {"type": "null"},
            {"$ref": "file://type/snowflake"}
        ]},
        "bitrate": {"type": "number", "inclusiveMinimum": 0},
        "user_limit": {"type": "number", "inclusiveMinimum": 0},
        "recipients": {"type": "array", "items": {"$ref": "file://object/user"}},
        "last_message_id": {"oneOf": [
            {"type": "null"},
            {"type": "string"}
        ]},
        "owner_id": {"oneOf": [
            {"type": "null"},
            {"$ref": "file://type/snowflake"}
        ]},
        "application_id": {"oneOf": [
            {"type": "null"},
            {"$ref": "file://type/snowflake"}
        ]},
        "parent_id": {"oneOf": [
            {"type": "null"},
            {"$ref": "file://type/snowflake"}
        ]},
        "last_pin_timestamp": {"type": "string"}
    }
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/object/marvin_pdu2_object_channel_test_1.json
{
    "id": "277784920368087040",
    "parent_id": "361119489477181442",
    "name": "Коммуна 'Pünzel Ariki'",
    "type": 2,
    "position": 7,
    "user_limit": 0,
    "bitrate": 64000,
    "permission_overwrites": [
        {
            "type": "role",
            "id": "269209661973069825",
            "deny": 36700160,
            "allow": 1024
        },
        {
            "type": "member",
            "id": "269871814010732546",
            "deny": 0,
            "allow": 36701184
        },
        {
            "type": "member",
            "id": "270791717190369283",
            "deny": 0,
            "allow": 36701184
        }
    ]
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/object/marvin_pdu2_object_channel_test_0.json
{
    "name": "welcome",
    "last_message_id": "269826707815530507",
    "id": "269209661973069825",
    "type": 0,
    "topic": "",
    "position": 0,
    "permission_overwrites": [
        {
            "type": "role",
            "id": "269213289978920960",
            "deny": 805763152,
            "allow": 65537
        },
        {
            "type": "role",
            "id": "269209661973069825",
            "deny": 805763153,
            "allow": 65536
        },
        {
            "type": "role",
            "id": "269213127835516929",
            "deny": 0,
            "allow": 0
        }
    ]
}
