=== cooladm1n/marvin/apps/marvin_pdu2/priv/json_schema/discord_gateway.json
{
    "id": "file://discord_gateway",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "https://discordapp.com/developers/docs/topics/gateway#payloads",
    "type": "object",
    "required": ["op", "d"],
    "properties": {
        "op": {"type": "number", "inclusiveMinimum": 0, "inclusiveMaximum": 11},
        "d": {
            "type": "object",
            "oneOf": [
                {"$ref": "file://pdu/dispatch/READY"},
                {"$ref": "file://pdu/dispatch/RESUMED"},
                {"$ref": "file://pdu/dispatch/CHANNEL_CREATE"},
                {"$ref": "file://pdu/dispatch/CHANNEL_UPDATE"},
                {"$ref": "file://pdu/dispatch/CHANNEL_DELETE"},
                {"$ref": "file://pdu/dispatch/GUILD_CREATE"},
                {"$ref": "file://pdu/dispatch/GUILD_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_DELETE"},
                {"$ref": "file://pdu/dispatch/GUILD_BAN_ADD"},
                {"$ref": "file://pdu/dispatch/GUILD_BAN_REMOVE"},
                {"$ref": "file://pdu/dispatch/GUILD_EMOJIS_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_INTEGRATIONS_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_MEMBER_ADD"},
                {"$ref": "file://pdu/dispatch/GUILD_MEMBER_REMOVE"},
                {"$ref": "file://pdu/dispatch/GUILD_MEMBER_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_MEMBERS_CHUNK"},
                {"$ref": "file://pdu/dispatch/GUILD_ROLE_CREATE"},
                {"$ref": "file://pdu/dispatch/GUILD_ROLE_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_ROLE_DELETE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_CREATE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_UPDATE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_DELETE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_DELETE_BULK"},
                {"$ref": "file://pdu/dispatch/MESSAGE_REACTION_ADD"},
                {"$ref": "file://pdu/dispatch/MESSAGE_REACTION_REMOVE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_REACTION_REMOVE_ALL"},
                {"$ref": "file://pdu/dispatch/PRESENCE_UPDATE"},
                {"$ref": "file://pdu/dispatch/TYPING_START"},
                {"$ref": "file://pdu/dispatch/USER_UPDATE"},
                {"$ref": "file://pdu/dispatch/VOICE_STATE_UPDATE"},
                {"$ref": "file://pdu/dispatch/VOICE_SERVER_UPDATE"},
                {"$ref": "file://pdu/heartbeat"},
                {"$ref": "file://pdu/identify"},
                {"$ref": "file://pdu/status_update"},
                {"$ref": "file://pdu/voice_state_update"},
                {"$ref": "file://pdu/voice_server_ping"},
                {"$ref": "file://pdu/resume"},
                {"$ref": "file://pdu/reconnect"},
                {"$ref": "file://pdu/request_guild_members"},
                {"$ref": "file://pdu/invalid_session"},
                {"$ref": "file://pdu/hello"},
                {"$ref": "file://pdu/heartbeat_ack"}
            ]
        },
        "s": {"type": "number", "exclusiveMinimum": 0},
        "t": {
            "type": "enum",
            "oneOf": [
                "READY", "RESUMED", "CHANNEL_CREATE", "CHANNEL_UPDATE", "CHANNEL_DELETE",
                "GUILD_CREATE", "GUILD_UPDATE", "GUILD_DELETE", "GUILD_BAN_ADD",
                "GUILD_BAN_REMOVE", "GUILD_EMOJIS_UPDATE", "GUILD_INTEGRATIONS_UPDATE",
                "GUILD_MEMBER_ADD", "GUILD_MEMBER_REMOVE", "GUILD_MEMBER_UPDATE",
                "GUILD_MEMBERS_CHUNK", "GUILD_ROLE_CREATE", "GUILD_ROLE_UPDATE",
                "GUILD_ROLE_DELETE", "MESSAGE_CREATE", "MESSAGE_UPDATE", "MESSAGE_DELETE",
                "MESSAGE_DELETE_BULK", "MESSAGE_REACTION_ADD", "MESSAGE_REACTION_REMOVE",
                "MESSAGE_REACTION_REMOVE_ALL", "PRESENCE_UPDATE", "TYPING_START",
                "USER_UPDATE", "VOICE_STATE_UPDATE", "VOICE_SERVER_UPDATE"
            ]
        }
    }
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_message_create_test_3.json
{
    "op": 0,
    "d": {
        "type": 0,
        "tts": false,
        "timestamp": "2018-03-26T18:13:59.664000+00:00",
        "pinned": false,
        "nonce": "427892995925213184",
        "mentions": [],
        "mention_roles": [
            "323193132441272331"
        ],
        "mention_everyone": false,
        "id": "427892994113404928",
        "embeds": [],
        "edited_timestamp": null,
        "content": "<@&323193132441272331> https://puu.sh/zQ16O/f0ff63b9eb.png\n<D0><9F><D1><80><D0><BE><D1><81><D1><82><D0><BE> <D0><BA><D0><BD><D0><BE><D0><BF><D0><BA><D1><83> <D1><82><D1><83><D1><86><D0><BD><D1><83><D1><82><D1><8C>\nhttps://worldofwarships.ru/ru/news/event/award_mo/",
        "channel_id": "269219052239585281",
        "author": {
            "username": "UrsusSapiens",
            "id": "271550397980737537",
            "discriminator": "7377",
            "avatar": "617c07c044803d35e97c62de46f65d96"
        },
        "attachments": []
    },
    "s": 1,
    "t": "MESSAGE_CREATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/pdu/marvin_pdu2_dispatch_guild_member_update_test_1.json
{
    "op": 0,
    "d": {
        "user": {
            "username": "acc1to",
            "id": "279344012228558849",
            "discriminator": "1626",
            "avatar": "ded696b466595850a4ca4f74a8599f37"
        },
        "roles": [
            "399572963881386006"
        ],
        "nick": null,
        "guild_id": "318325967602843658"
    },
    "s": 1337,
    "t": "GUILD_MEMBER_UPDATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_presence_update_test_1.json
{
    "op": 0,
    "d": {
        "user": {
            "id": "242257112208506881"
        },
        "status": "online",
        "roles": [],
        "nick": null,
        "guild_id": "269209661973069825",
        "game": {
            "type": 0,
            "timestamps": {
                "start": 1521747382640
            },
            "name": "League of Legends"
        }
    },
    "s": 1,
    "t": "PRESENCE_UPDATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/pdu/marvin_pdu2_dispatch_message_create_test_7.json
{
    "op": 0,
    "d": {
        "type": 0,
        "tts": false,
        "timestamp": "2018-05-30T15:55:43.379000+00:00",
        "pinned": false,
        "nonce": "451413407787122688",
        "mentions": [],
        "mention_roles": [],
        "mention_everyone": false,
        "member": {
            "roles": [
                "399557799811612704",
                "427217463693017088",
                "399587748283154432"
            ],
            "nick": null,
            "mute": false,
            "joined_at": "2017-05-28T12:32:43.223000+00:00",
            "deaf": false
        },
        "id": "451413408236044288",
        "guild_id": "318325967602843658",
        "embeds": [
            {
                "url": "https://www.dropbox.com/s/uqla3j21iv2as56/Screenshot%202018-05-30%2018.55.08.png?dl=0",
                "type": "article",
                "title": "Screenshot 2018-05-30 18.55.08.png",
                "thumbnail": {
                    "width": 1024,
                    "url": "https://www.dropbox.com/temp_thumb_from_token/s/uqla3j21iv2as56?preserve_transparency=False&size=1024x1024&size_mode=2",
                    "proxy_url": "https://images-ext-1.discordapp.net/external/Eqyt_ttmojkOTA6oI13aSCrp5xXmJtHPddqBbOv1Asg/%3Fpreserve_transparency%3DFalse%26size%3D1024x1024%26size_mode%3D2/https/www.dropbox.com/temp_thumb_from_token/s/uqla3j21iv2as56",
                    "height": 1024
                },
                "provider": {
                    "url": null,
                    "name": "Dropbox"
                },
                "description": "Shared with Dropbox"
            }
        ],
        "edited_timestamp": null,
        "content": "https://www.dropbox.com/s/uqla3j21iv2as56/Screenshot%202018-05-30%2018.55.08.png?dl=0",
        "channel_id": "448788687300591618",
        "author": {
            "username": "BizkitCake",
            "id": "143022070429646848",
            "discriminator": "8836",
            "avatar": "d526eca4a94c1810d72f9b0aebb12f4d"
        },
        "attachments": []
    },
    "s": 1,
    "t": "MESSAGE_CREATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_message_create_test_4.json
{
    "op": 0,
    "d": {
        "type": 0,
        "tts": false,
        "timestamp": "2018-03-26T13:42:16.692000+00:00",
        "pinned": false,
        "nonce": "427824604799565824",
        "mentions": [
            {
                "username": "Luciferius",
                "id": "255082434884927509",
                "discriminator": "9709",
                "avatar": "25d733eb8bf718fac8844148b5f7abe9"
            }
        ],
        "mention_roles": [],
        "mention_everyone": false,
        "id": "427824614492602379",
        "embeds": [
            {
                "video": {
                    "width": 1280,
                    "url": "https://www.youtube.com/embed/54iufAxoviI",
                    "height": 720
                },
                "url": "https://www.youtube.com/watch?v=54iufAxoviI",
                "type": "video",
                "title": "<D0><A5><D1><80><D0><B5><D0><BD> <D1><82><D0><B5><D0><B1><D0><B5> <D0><B2> <D1><80><D1><8B><D0><BB><D0><BE>! <D0><A1><D1><80><D0><B0><D0><BD><D1><8B><D0><B9> <D1><83><D1><80><D0><BE><D0><B4>",
                "thumbnail": {
                    "width": 1280,
                    "url": "https://i.ytimg.com/vi/54iufAxoviI/maxresdefault.jpg",
                    "proxy_url": "https://images-ext-1.discordapp.net/external/V30DMR0z6XW0xftHZZQR5MAzAy6r8xqX_0NdvKsDgEs/https/i.ytimg.com/vi/54iufAxoviI/maxresdefault.jpg",
                    "height": 720
                },
                "provider": {
                    "url": "https://www.youtube.com/",
                    "name": "YouTube"
                },
                "color": 16711680,
                "author": {
                    "url": "https://www.youtube.com/channel/UCiQ9_VDVdq4HZTAhNOsbARw",
                    "name": "Ruslan"
                }
            }
        ],
        "edited_timestamp": null,
        "content": "<@!255082434884927509> https://www.youtube.com/watch?v=54iufAxoviI",
        "channel_id": "269219052239585281",
        "author": {
            "username": "Mimi Virus",
            "id": "237296628250312706",
            "discriminator": "0562",
            "avatar": "4f1e32bc5876c76366d362862ed9f590"
        },
        "attachments": []
    },
    "s": 1,
    "t": "MESSAGE_CREATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_message_create_test_2.json
{
    "op": 0,
    "d": {
        "type": 0,
        "tts": false,
        "timestamp": "2018-03-26T11:49:46.616000+00:00",
        "pinned": false,
        "nonce": "427796301552287744",
        "mentions": [
            {
                "username": "<D0><BF><D0><B0><D0><BD><D0><B4><D0><B0>",
                "id": "270730226110038017",
                "discriminator": "2863",
                "avatar": "76bb64512f1ca00cdf9402934e35236c"
            }
        ],
        "mention_roles": [],
        "mention_everyone": false,
        "id": "427796302621835264",
        "embeds": [],
        "edited_timestamp": null,
        "content": "<@!270730226110038017> <:notsure:278508514652061710>",
        "channel_id": "269219052239585281",
        "author": {
            "username": "Punz",
            "id": "270791717190369283",
            "discriminator": "7187",
            "avatar": "01f3f46668c92c4ae51c405e4c1c984c"
        },
        "attachments": []
    },
    "s": 1,
    "t": "MESSAGE_CREATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/pdu/marvin_pdu2_dispatch_guild_member_update_test_2.json
{
    "op": 0,
    "d": {
        "user": {
            "username": "shizzard",
            "id": "269144761103810561",
            "discriminator": "1337",
            "avatar": "b061d4cf67e160f93661f59bb95f6934"
        },
        "roles": [
            "269213127835516929",
            "269213289978920960",
            "269565043446644739",
            "270845668619190273",
            "277189846664085505",
            "301042304880345088",
            "301058554821869569",
            "332188255824904193",
            "335395823196045313",
            "387273646663532544",
            "403106989678264333"
        ],
        "nick": null,
        "guild_id": "269209661973069825"
    },
    "s": 1337,
    "t": "GUILD_MEMBER_UPDATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_message_create_test_5.json
{
    "op": 0,
    "d": {
        "type": 0,
        "tts": false,
        "timestamp": "2018-03-29T10:45:37.108000+00:00",
        "pinned": false,
        "nonce": null,
        "mentions": [],
        "mention_roles": [],
        "mention_everyone": false,
        "id": "428867320212094996",
        "embeds": [
            {
                "url": "https://vk.com/imbasquad",
                "type": "rich",
                "title": "Here goes title",
                "timestamp": "2018-03-29T10:22:40.605000+00:00",
                "thumbnail": {
                    "width": 0,
                    "url": "https://cdn.discordapp.com/embed/avatars/0.png",
                    "proxy_url": "https://images-ext-2.discordapp.net/external/2dZVVL6feMSM7lxfFkKVW__LToSOzmToSEmocJV5vcA/https/cdn.discordapp.com/embed/avatars/0.png",
                    "height": 0
                },
                "image": {
                    "width": 0,
                    "url": "https://cdn.discordapp.com/embed/avatars/0.png",
                    "proxy_url": "https://images-ext-2.discordapp.net/external/2dZVVL6feMSM7lxfFkKVW__LToSOzmToSEmocJV5vcA/https/cdn.discordapp.com/embed/avatars/0.png",
                    "height": 0
                },
                "footer": {
                    "text": "Some footer",
                    "proxy_icon_url": "https://images-ext-2.discordapp.net/external/2dZVVL6feMSM7lxfFkKVW__LToSOzmToSEmocJV5vcA/https/cdn.discordapp.com/embed/avatars/0.png",
                    "icon_url": "https://cdn.discordapp.com/embed/avatars/0.png"
                },
                "fields": [
                    {
                        "value": "![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png) Dolor sit amet, consectetur adipiscing elit.",
                        "name": "Lorem ipsum",
                        "inline": false
                    },
                    {
                        "value": "Quisque venenatis erat eget faucibus dictum.",
                        "name": "Integer dignissim",
                        "inline": false
                    },
                    {
                        "value": "Integer dignissim felis eu lorem fringilla convallis.",
                        "name": "In porttitor",
                        "inline": false
                    },
                    {
                        "value": "![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png) Sed sit ametdui et ipsum semper porttitor.",
                        "name": "Nunc at mauris",
                        "inline": true
                    },
                    {
                        "value": "Nullam ornare diam scelerisque scelerisque feugiat.",
                        "name": "Mauris blandit",
                        "inline": true
                    }
                ],
                "description": "[Imbasquad vk.com](https://vk.com/imbasquad)",
                "color": 14654978,
                "author": {
                    "url": "https://github.com/shizzard/marvin",
                    "proxy_icon_url": "https://images-ext-2.discordapp.net/external/2dZVVL6feMSM7lxfFkKVW__LToSOzmToSEmocJV5vcA/https/cdn.discordapp.com/embed/avatars/0.png",
                    "name": "Marvin",
                    "icon_url": "https://cdn.discordapp.com/embed/avatars/0.png"
                }
            }
        ],
        "edited_timestamp": null,
        "content": "**TEST MESSAGE**",
        "channel_id": "341496525613957120",
        "author": {
            "username": "Marvin",
            "id": "341500172515278859",
            "discriminator": "8455",
            "bot": true,
            "avatar": "1888f192aa92e3de15f795df27c8475e"
        },
        "attachments": []
    },
    "s": 1,
    "t": "MESSAGE_CREATE"
}
