=== cooladm1n/marvin/apps/marvin_pdu2/priv/json_schema/discord_gateway.json
{
    "id": "file://discord_gateway",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "https://discordapp.com/developers/docs/topics/gateway#payloads",
    "type": "object",
    "required": ["op", "d"],
    "properties": {
        "op": {"type": "number", "inclusiveMinimum": 0, "inclusiveMaximum": 11},
        "d": {
            "type": "object",
            "oneOf": [
                {"$ref": "file://pdu/dispatch/READY"},
                {"$ref": "file://pdu/dispatch/RESUMED"},
                {"$ref": "file://pdu/dispatch/CHANNEL_CREATE"},
                {"$ref": "file://pdu/dispatch/CHANNEL_UPDATE"},
                {"$ref": "file://pdu/dispatch/CHANNEL_DELETE"},
                {"$ref": "file://pdu/dispatch/GUILD_CREATE"},
                {"$ref": "file://pdu/dispatch/GUILD_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_DELETE"},
                {"$ref": "file://pdu/dispatch/GUILD_BAN_ADD"},
                {"$ref": "file://pdu/dispatch/GUILD_BAN_REMOVE"},
                {"$ref": "file://pdu/dispatch/GUILD_EMOJIS_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_INTEGRATIONS_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_MEMBER_ADD"},
                {"$ref": "file://pdu/dispatch/GUILD_MEMBER_REMOVE"},
                {"$ref": "file://pdu/dispatch/GUILD_MEMBER_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_MEMBERS_CHUNK"},
                {"$ref": "file://pdu/dispatch/GUILD_ROLE_CREATE"},
                {"$ref": "file://pdu/dispatch/GUILD_ROLE_UPDATE"},
                {"$ref": "file://pdu/dispatch/GUILD_ROLE_DELETE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_CREATE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_UPDATE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_DELETE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_DELETE_BULK"},
                {"$ref": "file://pdu/dispatch/MESSAGE_REACTION_ADD"},
                {"$ref": "file://pdu/dispatch/MESSAGE_REACTION_REMOVE"},
                {"$ref": "file://pdu/dispatch/MESSAGE_REACTION_REMOVE_ALL"},
                {"$ref": "file://pdu/dispatch/PRESENCE_UPDATE"},
                {"$ref": "file://pdu/dispatch/TYPING_START"},
                {"$ref": "file://pdu/dispatch/USER_UPDATE"},
                {"$ref": "file://pdu/dispatch/VOICE_STATE_UPDATE"},
                {"$ref": "file://pdu/dispatch/VOICE_SERVER_UPDATE"},
                {"$ref": "file://pdu/heartbeat"},
                {"$ref": "file://pdu/identify"},
                {"$ref": "file://pdu/status_update"},
                {"$ref": "file://pdu/voice_state_update"},
                {"$ref": "file://pdu/voice_server_ping"},
                {"$ref": "file://pdu/resume"},
                {"$ref": "file://pdu/reconnect"},
                {"$ref": "file://pdu/request_guild_members"},
                {"$ref": "file://pdu/invalid_session"},
                {"$ref": "file://pdu/hello"},
                {"$ref": "file://pdu/heartbeat_ack"}
            ]
        },
        "s": {"type": "number", "exclusiveMinimum": 0},
        "t": {
            "type": "enum",
            "oneOf": [
                "READY", "RESUMED", "CHANNEL_CREATE", "CHANNEL_UPDATE", "CHANNEL_DELETE",
                "GUILD_CREATE", "GUILD_UPDATE", "GUILD_DELETE", "GUILD_BAN_ADD",
                "GUILD_BAN_REMOVE", "GUILD_EMOJIS_UPDATE", "GUILD_INTEGRATIONS_UPDATE",
                "GUILD_MEMBER_ADD", "GUILD_MEMBER_REMOVE", "GUILD_MEMBER_UPDATE",
                "GUILD_MEMBERS_CHUNK", "GUILD_ROLE_CREATE", "GUILD_ROLE_UPDATE",
                "GUILD_ROLE_DELETE", "MESSAGE_CREATE", "MESSAGE_UPDATE", "MESSAGE_DELETE",
                "MESSAGE_DELETE_BULK", "MESSAGE_REACTION_ADD", "MESSAGE_REACTION_REMOVE",
                "MESSAGE_REACTION_REMOVE_ALL", "PRESENCE_UPDATE", "TYPING_START",
                "USER_UPDATE", "VOICE_STATE_UPDATE", "VOICE_SERVER_UPDATE"
            ]
        }
    }
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/pdu/marvin_pdu2_dispatch_message_create_test_8.json
{
    "op": 0,
    "d": {
        "type": 0,
        "tts": false,
        "timestamp": "2018-06-01T18:07:46.888000+00:00",
        "pinned": false,
        "nonce": null,
        "mentions": [],
        "mention_roles": [],
        "mention_everyone": false,
        "member": {
            "roles": [
                "451421298204213258",
                "448779403925651463"
            ],
            "nick": null,
            "mute": false,
            "joined_at": "2018-05-23T09:29:07.808830+00:00",
            "deaf": false
        },
        "id": "452171417572868107",
        "guild_id": "318325967602843658",
        "embeds": [
            {
                "url": "https://www.twitch.tv/pur_purr_purrr",
                "type": "rich",
                "title": "Пуррхай как бабочка, жаль что не дайм | ОВЕРВОТЧ!",
                "thumbnail": {
                    "width": 0,
                    "url": "https://static-cdn.jtvnw.net/jtv_user_pictures/9a5c1439-34c4-489d-9af3-0bd854ee574f-profile_image-300x300.jpg",
                    "proxy_url": "https://images-ext-1.discordapp.net/external/b27_zcOQnh-M6AAIk5QqxKacpMLDIRJ-L7hfKsy9JIk/https/static-cdn.jtvnw.net/jtv_user_pictures/9a5c1439-34c4-489d-9af3-0bd854ee574f-profile_image-300x300.jpg",
                    "height": 0
                },
                "image": {
                    "width": 0,
                    "url": "https://static-cdn.jtvnw.net/previews-ttv/live_user_pur_purr_purrr-320x180.jpg?r=217629",
                    "proxy_url": "https://images-ext-2.discordapp.net/external/QRefLHsRB68djPrlssICGc97mZx4uqlvYPfYSgIMDBI/%3Fr%3D217629/https/static-cdn.jtvnw.net/previews-ttv/live_user_pur_purr_purrr-320x180.jpg",
                    "height": 0
                },
                "fields": [
                    {
                        "value": "Overwatch",
                        "name": "Game",
                        "inline": true
                    },
                    {
                        "value": "1",
                        "name": "Viewers",
                        "inline": true
                    }
                ],
                "color": 6570404,
                "author": {
                    "proxy_icon_url": "https://images-ext-1.discordapp.net/external/b27_zcOQnh-M6AAIk5QqxKacpMLDIRJ-L7hfKsy9JIk/https/static-cdn.jtvnw.net/jtv_user_pictures/9a5c1439-34c4-489d-9af3-0bd854ee574f-profile_image-300x300.jpg",
                    "name": "pur_purr_purrr",
                    "icon_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/9a5c1439-34c4-489d-9af3-0bd854ee574f-profile_image-300x300.jpg"
                }
            }
        ],
        "edited_timestamp": null,
        "content": "Клац-клац, хлопци и дивчины, pur_purr_purrr запустила стримулю https://www.twitch.tv/pur_purr_purrr ! Бронза фтв!",
        "channel_id": "399552308486340608",
        "author": {
            "username": "MEE6",
            "id": "159985870458322944",
            "discriminator": "4876",
            "bot": true,
            "avatar": "8c7187aa71f15ba271c85bfece9b067e"
        },
        "attachments": []
    },
    "s": 1,
    "t": "MESSAGE_CREATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_message_create_test_6.json
{
    "op": 0,
    "d": {
        "type": 0,
        "tts": false,
        "timestamp": "2018-04-04T15:04:12.329000+00:00",
        "pinned": false,
        "nonce": "431106722510143488",
        "mentions": [],
        "mention_roles": [],
        "mention_everyone": false,
        "id": "431106722958934016",
        "embeds": [
            {
                "url": "https://cs8.pikabu.ru/post_img/2018/04/04/7/1522836843218387727.gif",
                "type": "image",
                "thumbnail": {
                    "width": 320,
                    "url": "https://cs8.pikabu.ru/post_img/2018/04/04/7/1522836843218387727.gif",
                    "proxy_url": "https://images-ext-1.discordapp.net/external/y6P8Ysso1LFK_Jy-b7WLNo10JY662IgArd1QsbaD69c/https/cs8.pikabu.ru/post_img/2018/04/04/7/1522836843218387727.gif",
                    "height": 181
                }
            }
        ],
        "edited_timestamp": null,
        "content": "https://cs8.pikabu.ru/post_img/2018/04/04/7/1522836843218387727.gif",
        "channel_id": "296248793823838208",
        "author": {
            "username": "shizzard",
            "id": "269144761103810561",
            "discriminator": "1337",
            "avatar": "d84d52bad1159c063d043a074b3a1703"
        },
        "attachments": []
    },
    "s": 1,
    "t": "MESSAGE_CREATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_message_create_test_0.json
{
    "op": 0,
    "d": {
        "type": 0,
        "tts": false,
        "timestamp": "2018-03-26T11:49:25.312000+00:00",
        "pinned": false,
        "nonce": "433966993255694336",
        "mentions": [],
        "mention_roles": [],
        "mention_everyone": false,
        "id": "427796213266513920",
        "embeds": [],
        "edited_timestamp": null,
        "content": "А играл в танки, таких проблем не было бы",
        "channel_id": "269219052239585281",
        "author": {
            "username": "Luciferius",
            "id": "255082434884927509",
            "discriminator": "9709",
            "avatar": "25d733eb8bf718fac8844148b5f7abe9"
        },
        "attachments": []
    },
    "s": 1,
    "t": "MESSAGE_CREATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_presence_update_test_2.json
{
    "op": 0,
    "d": {
        "user": {
            "id": "268824010974822412"
        },
        "status": "idle",
        "roles": [
            "301043143292354570"
        ],
        "nick": "Макаронный Бог",
        "guild_id": "269209661973069825",
        "game": null
    },
    "s": 1,
    "t": "PRESENCE_UPDATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_presence_update_test_0.json
{
    "op": 0,
    "d": {
        "user": {
            "id": "329121622701375489"
        },
        "status": "idle",
        "roles": [
            "270845668619190273"
        ],
        "nick": null,
        "guild_id": "269209661973069825",
        "game": null
    },
    "s": 1,
    "t": "PRESENCE_UPDATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_message_create_test_1.json
{
    "op": 0,
    "d": {
        "type": 0,
        "tts": false,
        "timestamp": "2018-03-26T18:30:36.662000+00:00",
        "pinned": false,
        "nonce": null,
        "mentions": [],
        "mention_roles": [],
        "mention_everyone": false,
        "id": "427897175826235403",
        "embeds": [],
        "edited_timestamp": null,
        "content": "",
        "channel_id": "296248793823838208",
        "author": {
            "username": "Deathtechnikk",
            "id": "397025970076254226",
            "discriminator": "8415",
            "avatar": "f2dd523b2c783f4246cbbe204494661a"
        },
        "attachments": [
            {
                "width": 640,
                "url": "https://cdn.discordapp.com/attachments/296248793823838208/427897175826235402/11260474.png",
                "size": 242217,
                "proxy_url": "https://media.discordapp.net/attachments/296248793823838208/427897175826235402/11260474.png",
                "id": "427897175826235402",
                "height": 581,
                "filename": "11260474.png"
            }
        ]
    },
    "s": 1,
    "t": "MESSAGE_CREATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/pdu/marvin_pdu2_dispatch_presence_update_test_4.json
{
    "op": 0,
    "d": {
        "user": {
            "id": "321283856017784833"
        },
        "status": "online",
        "roles": [],
        "nick": null,
        "guild_id": "318325967602843658",
        "game": {
            "type": 3,
            "name": "на битовые часы: 22:50 UTC"
        }
    },
    "s": 1,
    "t": "PRESENCE_UPDATE"
}

=== cooladm1n/marvin/apps/marvin_pdu2/priv/test_cases/pdu/marvin_pdu2_dispatch_ready_test_0.json
{
    "op": 0,
    "d": {
        "_trace": [
            "discord-gateway-prd-1-27",
            "discord-sessions-prd-1-15"
        ],
        "guilds": [{
            "id": "269209661973069825", "unavailable": true
        }],
        "private_channels": [],
        "session_id": "b1d4c1953ab135bb90a700e10957ec15",
        "user": {
            "avatar": "1888f192aa92e3de15f795df27c8475e",
            "bot": true,
            "discriminator": "8455",
            "email": null,
            "id": "341500172515278859",
            "mfa_enabled": false,
            "username": "Marvin",
            "verified": true
        },
        "v": 6
    },
    "s": 1,
    "t": "READY"
}
